name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    env:
      API_KEY: ${{ secrets.API_KEY }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Debug secrets
        run: echo "Actions read \${API_KEY} is [$API_KEY]"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

  run-docker-image-on-ec2:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

      - name: Stop and remove old container
        run: |
          if [ $(sudo docker ps -a -q -f name=spring-cicd-test) ]; then
            sudo docker stop spring-cicd-test
            sudo docker rm spring-cicd-test
          fi
      - name: Debug container env
        run: |
          sudo docker run --rm \
            -e API_KEY=${{ secrets.API_KEY }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test \
            sh -c 'echo CONTAINER sees: $API_KEY'

      - name: Run new container
        run: |
          sudo docker run -it -d \
            -p 8080:8080 \
            -e spring.ai.openai.api-key=${{ secrets.API_KEY }} \
            --name spring-cicd-test \
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

      - name: Delete unused Docker images
        run: sudo docker system prune -f

